### PR TITLE
fix: crash when executing on server side

### PR DESCRIPTION
**Pull request by ruizmarc**
Fix issue: https://github.com/MurhafSousli/ngx-scrollbar/issues/267

### CODE REVIEW

**Comment by MurhafSousli** [comment]
Thank you!

**Comment by ruizmarc** [comment]
It would be great to have this fix released soon on NPM :)

**Comment by MurhafSousli** [comment]
Hopefully this weekend

**Comment by MurhafSousli** [comment]
Released v7.3.0 for the fix!

**Pull request merged**
