### PR TITLE
Fix tests failing randomly 

### LINKED ISSUE #278: test fail randomly
After upgrading to Angular 9, the test fails **sometimes**.

If anyone knows how to fix it, help is appreciated!

Screenshot 2020-03-13 at 19 01 22

### PR DESCRIPTION
**Pull request by f4irline**
Closes #278

### CODE REVIEW

**Comment by f4irline** [comment]
Mmeh, looks like they fail even with this change. I was able to run the tests successfully very consistently, but all of a sudden they seem to be failing again. I'll have to investigate more.

**Comment by MurhafSousli** [comment]
@f4irline Thank you, the tests used to run in order and it always pass. but this happened only after upgrading to angular 9.

**Comment by f4irline** [comment]
Adding the `fixture.destroy();` in the `afterAll()` hook seemed to fix most of the issues, but occasionally one of the tests would still fail. After I removed the `async` declaration from the `beforeEach()` hook (where the TestBed was configured), I could not reproduce the issue anymore.

**Comment by f4irline** [comment]
> @f4irline Thank you, the tests used to run in order and it always pass. but this happened only after upgrading to angular 9.

Adding the `fixture.destroy();` in the `afterAll()` hook seemed to fix most of the issues, but occasionally one of the tests would still fail. After I removed the `async` declaration from the `beforeEach()` hook (where the TestBed was configured), I could not reproduce the issue anymore!

**Comment by MurhafSousli** [comment]
Thank you very much!

**Pull request merged**
