### PR TITLE
fix: prevent error "ResizeObserver loop completed with undelivered notifications"

### LINKED ISSUE #650: ResizeObserver loop completed with undelivered notifications
#### Reproduction

I am not able to provide a reproduction - it seems this is only happening with some "load".
But I was able to patch this library locally to fix this problem - I'll provide a PR immediately!

This error can be observed in Firefox by
 ```js
  window.addEventListener('error', function (e) {
    console.error('Error occurred: ', e, e.composedPath());
  });
```
 
#### Expected Behavior

This error should not happen under regular circumsstances - see https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors

#### Actual Behavior

Error:
```
ResizeObserver loop completed with undelivered notifications.
```

#### Environment

- Angular: 18.1.1
- ngx-scrollbar: 15.1.3
- Browser(s): Firefox (+ probably Safari)
- Operating System (e.g. Windows, macOS, Ubuntu): Win10

### PR DESCRIPTION
**Pull request by daniel-sc**
see https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors 
fixes #650

### CODE REVIEW

**Comment by daniel-sc** [comment]
@MurhafSousli I was not able to get the test running on my machine - maybe you could adjust them for the fix?

**Comment by MurhafSousli** [comment]
@daniel-sc Thanks for bringing this up, in the next update, the component will use a shared resize observer from the CDK where this use case is handled

https://github.com/angular/components/blob/2dd269e63124f8bbb30c58969b3fd8dde46283e9/src/cdk/observers/private/shared-resize-observer.ts#L17-L23

**Comment by daniel-sc** [comment]
@MurhafSousli thanks for picking this up! 
I am not 100% sure the shared resize observer resolves this problem - the linked code only indicates a better error logging (which is great of course), but I could not find if/where  `requestAnimationFrame` or some other delaying is used to prevent the error from happening in the first place?

**Comment by MurhafSousli** [comment]
@daniel-sc As I understood this only happens if you have code in the resize observer callback that might change the size again, such as modifying the width / height / margin / padding which triggers the resize event again, causing an infinite loop. in our case we don't have code that changes the size.

**Comment by daniel-sc** [comment]
@MurhafSousli You are probably deeper into this topic, so please don't get confused by my semi know how. My understanding was that there was some resizing done in the observer before (otherwise there would have been no error) - since the logic did not change, it  will trigger the same error (using a shared or a dedicated ResizeObserver should make no difference)? But maybe my assumptions are wrong. Maybe you could cut a pre release and I'll check if the error still persists?

**Comment by MurhafSousli** [comment]
I released a beta version `npm i ngx-scrollbar@beta`, could you pressure test it?

**Pull request closed without merging**
